version: '3'

vars:
  NAME          : netcheck
  DESCRIPTION   : Simple probe to check network connectivity.
  COPYRIGHT     : 2024 © Andrea Funtò
  LICENSE       : MIT
  LICENSE_URL   : https://opensource.org/license/mit/
  VERSION_MAJOR : 1
  VERSION_MINOR : 0
  VERSION_PATCH : 2
  MAINTAINER    : dihedron.dev@gmail.com
  VENDOR        : dihedron.dev@gmail.com
  RELEASE       : 1
  PRODUCER_URL  : https://github.com/dihedron/
  DOWNLOAD_URL  : '{{.PRODUCER_URL}}netcheck'
  SUPPORTED_PLATFORMS:
    sh: go tool dist list
  VERSION: '{{.VERSION_MAJOR}}.{{.VERSION_MINOR}}.{{.VERSION_PATCH}}'

tasks:

  default:
    vars:
      PLATFORM: 'linux/amd64'
    cmds:
      - task: build
        vars:
          PLATFORM: '{{ .PLATFORM }}'
      - task: deb
        vars:
          PLATFORM: '{{ .PLATFORM }}'
      - task: rpm
        vars:
          PLATFORM: '{{ .PLATFORM }}'

  #
  # clean removes all output directies
  #
  clean:
    cmds: 
      - rm -rf dist/

  #
  # some builds the
  some:
    requires:
      vars: [CLI_ARGS]
    vars:
      PLATFORMS: '{{ .CLI_ARGS }}'
    cmds:
      - for: { var: PLATFORMS }
        task: build
        vars:
          PLATFORM: '{{ .ITEM }}'
      - for: { var: PLATFORMS }
        task: deb
        vars:
          PLATFORM: '{{ .ITEM }}'
      - for: { var: PLATFORMS }
        task: rpm
        vars:
          PLATFORM: '{{ .ITEM }}'

  all:
    vars:
      PLATFORMS:
        sh: go tool dist list
    cmds:
      - for: { var: PLATFORMS }
        task: build
        vars:
          PLATFORM: '{{ .ITEM }}'

  #
  # build builds the application for a specific PLATFORM
  #
  build:
    requires:
      vars: [PLATFORM]
    vars:
      MODULE: 
        sh: grep "module .*" go.mod | sed 's/module //gi'
      PACKAGE: '{{.MODULE}}/version'
      NOW: 
        sh: date --rfc-3339=seconds
      GOOS: '{{ $array := split "/" .PLATFORM }}{{ $array._0 }}'
      GOARCH: '{{ $array := split "/" .PLATFORM }}{{ $array._1 }}'
      GOAMD64: v3
      CGO_ENABLED: 0
    cmds:
      - task: check-platform-support
        vars:
          PLATFORM: '{{ .PLATFORM }}'
      - echo Building {{ .MODULE }} ver. {{ .VERSION }} for {{ .GOOS }}/{{ .GOARCH }}...
      - task: check-vulnerabilities
      - task: run-go-generate
      - task: make-output-dir
        vars:
          PLATFORM: '{{ .PLATFORM }}'
      - CGO_ENABLED={{.CGO_ENABLED}} go build -v -ldflags="-w -s -X '{{.PACKAGE}}.Name={{.NAME}}' -X '{{.PACKAGE}}.Description={{.DESCRIPTION}}' -X '{{.PACKAGE}}.Copyright={{.COPYRIGHT}}' -X '{{.PACKAGE}}.License={{.LICENSE}}' -X '{{.PACKAGE}}.LicenseURL={{.LICENSE_URL}}' -X '{{.PACKAGE}}.BuildTime={{.NOW}}' -X '{{.PACKAGE}}.VersionMajor={{.VERSION_MAJOR}}' -X '{{.PACKAGE}}.VersionMinor={{.VERSION_MINOR}}' -X '{{.PACKAGE}}.VersionPatch={{.VERSION_PATCH}}'" -o dist/{{.PLATFORM}}/ .

  #
  # deb packages the application in DEB format
  #
  deb:
    requires:
      vars: [PLATFORM]
    vars: 
      PLATFORM: '{{.PLATFORM}}'
      VERSION: '{{.VERSION}}'
    cmds: 
      - VERSION={{.VERSION}} nfpm package --packager deb --target dist/{{.PLATFORM}}

  #
  # rpm packages the application in RPM format
  #
  rpm:
    requires:
      vars: [PLATFORM]
    cmds: 
      - VERSION={{.VERSION}} nfpm package --packager rpm --target dist/{{.PLATFORM}}


  #
  # check-platform-support checks if the provided platform is among 
  # those supported by the golang compiler
  #
  check-platform-support:
    requires:
      vars: [PLATFORM]
    vars:
      SUPPORTED: '{{ $ALL_PLATFORMS := splitList "\n" .SUPPORTED_PLATFORMS }} {{ has .PLATFORM $ALL_PLATFORMS }}'
    cmds: 
      - echo 'Is platform {{ .PLATFORM }} supported? {{- .SUPPORTED }}'
      - if {{- .SUPPORTED }}; then exit 0; else exit 1; fi 
      
  #
  # check-vulnerabilities runs govulncheck agains the project dependencies
  # to check if there re any outstanding vulnerabilities
  #
  check-vulnerabilities:
    run: once
    cmds:
      - govulncheck ./...

  #
  # run-go-generate runs go generate against the sources
  #
  run-go-generate:
    run: once
    cmds:
      - go generate ./...

  #
  # make-output-dir creates the output directory for the given platform
  #
  make-output-dir:
    requires:
      vars: [PLATFORM]
    status:
      - test -d dist/{{ .PLATFORM }}
    cmds:
      - echo creating directy
      - mkdir -p dist/{{ .PLATFORM }}

  #
  # setup-tools installs all the required tools
  #
  setup-tools:
    cmds:
      - go install golang.org/x/vuln/cmd/govulncheck@latest
      - go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest

  # check-govulncheck:
  #   run: once
  #   cmds:
  #     - go install golang.org/x/vuln/cmd/govulncheck@latest
  #   generates:
  #     - '{{.GOPATH}}/bin/govulncheck'
  #   status:
  #     - test -f {{.GOPATH}}/bin/govulncheck

  # check-nfpm:
  #   run: once
  #   cmds:
  #   status:
  #     - test -f {{.GOPATH}}/bin/nfpm