name: Continuous Build

on:
  push:
    branches:
      - "**"
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go compiler
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"

      - name: Ensure GoReleaser is installed
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: "~> v2"
          install-only: true

      - name: Run Makefile target
        run: make
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Run Go Tests
      #   run: go test -v -coverprofile=coverage.out ./...

      # - name: Convert Coverage to Cobertura XML format
      #   run: |
      #     go install github.com/axw/gocov/gocov@latest
      #     go install github.com/AlekSi/gocov-xml@latest
      #     gocov convert coverage.out | gocov-xml > coverage.cobertura.xml

      # - name: Code Coverage Summary Report
      #   uses: irongut/CodeCoverageSummary@v1.3.0
      #   with:
      #     filename: coverage.cobertura.xml
      #     badge: true
      #     fail_below_min: false
      #     format: markdown
      #     output: both
      #     thresholds: '60 80'

      # - name: Add Coverage Summary to Action Run
      #   run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
