timeout = 20000000000
parallelism = 10

[[endpoints]]
timeout = 10000000000
address = 'www.repubblica.it'
port = 443
protocol = 'tcp'

[[endpoints]]
timeout = 10000000000
address = 'www.google.com'
port = 443
protocol = 'tcp'